<?php

namespace Database\Seeders;

use App\Models\BasisPengetahuan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DataPengetahuan extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        BasisPengetahuan::insert([
            //PET/PETE
            ['id'=>"1",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P001', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"2",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P002', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"3",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P003', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"4",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P004', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"5",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P005', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"6",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P006', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"07",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P007', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"08",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P008', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"9",  'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P010', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"10" , 'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P012', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"11" , 'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P014', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"12" , 'jenis_kemasan_id' => 'K001', 'kriteria_id' => 'P011', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //HDPE
            ['id'=>"13", 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P001', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"14" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P002', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"15" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P003', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ], 
            ['id'=>"16" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P004', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"17" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P005', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"18" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P007', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"19" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P008', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"20" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P010', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"21" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P011', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"22" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P013', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"23" , 'jenis_kemasan_id' => 'K002', 'kriteria_id' => 'P014', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //PVC
            ['id'=>"24", 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P001', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"25" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P002', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"26" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P003', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['id'=>"27" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P004', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"28" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P005', 'cf' => '0.2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"29" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P006', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"30" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P007', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"31" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P008', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"32" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P010', 'cf' => '0.2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"33" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P011', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"34" , 'jenis_kemasan_id' => 'K003', 'kriteria_id' => 'P013', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            
            //LDPE
            ['id'=>"35" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P001', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"36" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P002', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['id'=>"37" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P003', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['id'=>"38" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P004', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"39" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P005', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"40" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P006', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"41" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P007', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"42" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P008', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"43" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P010', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"44" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P011', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"45" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P013', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"46" , 'jenis_kemasan_id' => 'K004', 'kriteria_id' => 'P014', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
        
            //PP
            ['id'=>"47" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P001', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"48" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P002', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['id'=>"49" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P003', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['id'=>"50" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P005', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"51" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P006', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"52" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P007', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"53" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P008', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"54" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P010', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"55" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P011', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"56" , 'jenis_kemasan_id' => 'K005', 'kriteria_id' => 'P014', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //PS
            ['id'=>"57" , 'jenis_kemasan_id' => 'K006', 'kriteria_id' => 'P001', 'cf' => '0.2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"58" , 'jenis_kemasan_id' => 'K006', 'kriteria_id' => 'P002', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['id'=>"59" , 'jenis_kemasan_id' => 'K006', 'kriteria_id' => 'P005', 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"60" , 'jenis_kemasan_id' => 'K006', 'kriteria_id' => 'P006', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"61" , 'jenis_kemasan_id' => 'K006', 'kriteria_id' => 'P007', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"62" , 'jenis_kemasan_id' => 'K006', 'kriteria_id' => 'P008', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //NYLON
            ['id'=>"63" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P001', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"64" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P002', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],  
            ['id'=>"65" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P003', 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"66" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P004', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"67" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P005', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"68" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P006', 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ], 
            ['id'=>"69" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P009', 'cf' => '0.2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"70" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P010', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['id'=>"71" , 'jenis_kemasan_id' => 'K007', 'kriteria_id' => 'P011', 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
        ]);
}
}