<?php

namespace Database\Seeders;

use App\Models\BasisPengetahuan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DataPengetahuan extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        BasisPengetahuan::insert([
            //PET/PETE
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 1, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 2, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 3, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 4, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 5, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 7, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 9, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 10, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            [ 'jenis_kemasan_id' => 1, 'kriteria_id' => 11, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 1, 'kriteria_id' => 13, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 1, 'kriteria_id' => 14, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 1, 'kriteria_id' => 15, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 1, 'kriteria_id' => 16, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 1, 'kriteria_id' => 18, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 1, 'kriteria_id' => 19, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //HDPE
            [ 'jenis_kemasan_id' => 2, 'kriteria_id' => 1, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 2, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 4, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ], 
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 5, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 7, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 8, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 9, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 10, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 12, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 13, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 14, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 15, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 16, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 17, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 18, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 19, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 2, 'kriteria_id' => 20, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //PVC
            [ 'jenis_kemasan_id' => 3, 'kriteria_id' => 1, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 2, 'cf' => '0.2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 3, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 4, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 5, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 7, 'cf' => '0.2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 9, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 10, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 12, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 14, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 15, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 16, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 18, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 3, 'kriteria_id' => 19, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            
            //LDPE
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 1, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 2, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 3, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 4, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 5, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 7, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 9, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 10, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 12, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 13, 'cf' => '0.4', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 14, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 15, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 16, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 17, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 18, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 4, 'kriteria_id' => 19, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //PP
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 2, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 3, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 4, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],   
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 5, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 7, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 10, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 13, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 14, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 15, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 16, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 17, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 18, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 19, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 5, 'kriteria_id' => 20, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],

            //NYLON
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 1, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 2, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],  
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 3, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 6, 'cf' => '0,2', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 7, 'cf' => '0,6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 8, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ], 
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 9, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 10, 'cf' => '0.6', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 14, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 15, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 16, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 17, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 18, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 19, 'cf' => '1', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
            ['jenis_kemasan_id' => 6, 'kriteria_id' => 20, 'cf' => '0.8', 'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s") ],
        ]);
}
}